### ISSUE TITLE
Why is packager located in deeplinks?

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/npm-packager#54]
### Describe the issue

I have found that deeplinks contains packager links: 
https://github.com/deep-foundation/deeplinks/blob/26cb67fd59fcc4f727b80356fa417fcbe53455ea/imports/packager.ts#L25
Why are not they moved to this package?

### Expected behavior

Packager code is located at `npm-packager` repository

**Comment by Konard** [comment]
Because Packager is general logic and it should be in deeplinks. NPM packager is only for NPM. We will have multiple packager for PyPi, Maven, NuGet, Cargo and so on.
