### ISSUE TITLE
don't publish package

### ISSUE THREAD

**Issue by Tand-Anthros** [deep-foundation/npm-packager#96]
```javascript
{
  "stack": "TypeError: Cannot read properties of null (reading 'value')\n    at loadNpmToken (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:107:38)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async eval (eval at memoized (/node_modules/lodash/memoize.js:62:23), <anonymous>:205:22)",
  "message": "Cannot read properties of null (reading 'value')"
}
```

![Screenshot_20240315_024218](https://github.com/deep-foundation/deepcase-app/assets/46575763/803cb5aa-125f-4d0c-896e-43b8d3ad2479)

![Screenshot_20240315_024928](https://github.com/deep-foundation/deepcase-app/assets/46575763/07766e54-a63f-484f-a2a8-ca59f2f3921d)

![Screenshot_20240315_025327](https://github.com/deep-foundation/deepcase-app/assets/46575763/6dba963d-25fc-4d68-98f9-7b48909bafa6)

**Comment by Konard** [comment]
To fix the problem, make sure you have a value for `Token` link instance contained within `admin` user.

The bug here also the error message itself, it should be a well-formed error message that will be easy for user to understand.
